theme: jekyll-theme-minimal
title: Brittney Ho | Reporting in the Digital Age 
description: Here are some projects that I've compiled over the past few months, all documented on this RMarkdown-driven website. 
